# @package model

vision_arch: vit_tiny_patch16_224.augreg_in21k_ft_in1k
text_arch: HuggingFaceTB/SmolLM2-135M
embed_dim: 512
use_lora: true
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05

loss: cross-entropy
initial_logit_scale: 2.6592
initial_logit_bias: 0.0

learning_rate: 5.0e-4
weight_decay: 0.05
warmup_steps: 10
backbone_lr_scale_after_unfreeze: 1.0

vocab_size: -1
img_token_id: -1
