# @package _global_

defaults:
  - data: fashion_iq
  - model: collm
  - trainer: finetune
  - logging: mlflow
  - inference: onnx
  - _self_

seed: 42
project_name: fashion-finder

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true

paths:
  data_root: data
  checkpoints_root: checkpoints
  resume_from: null
